train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ubuntu/data/main/tableSR/frames/nemo/Vlogs/540p/videoplayback2
      root_path_2: /home/ubuntu/data/main/tableSR/frames/nemo/Vlogs/1080raw/videoplayback2
      repeat: 64
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
      augment: true
  batch_size: 32

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ubuntu/data/main/tableSR/frames/nemo/Vlogs/540p/videoplayback2
      root_path_2: /home/ubuntu/data/main/tableSR/frames/nemo/Vlogs/1080raw/videoplayback2
      repeat: 8
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
  batch_size: 32

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
    name: patchSR
    args:
      scale: 2
      p: 3

#resume: /home/ubuntu/data/main/tableSR/model/Vlogs_playback2_patchSR/epoch-last.pth
optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 300
multi_step_lr:
  milestones: [100, 200, 300]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
