train_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ubuntu/data/home/main/SR_Test/namo_data
      root_path_2: /home/ubuntu/data/home/main/SR_Test/namo_data
      repeat: 32
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
      augment: true
  batch_size: 32

val_dataset:
  dataset:
    name: paired-image-folders
    args:
      root_path_1: /home/ubuntu/data/home/main/SR_Test/namo_data
      root_path_2: /home/ubuntu/data/home/main/SR_Test/namo_data
      repeat: 1
      cache: in_memory
  wrapper:
    name: sr-implicit-paired
    args:
      inp_size: 48
  batch_size: 32

data_norm:
  inp: {sub: [0.5], div: [0.5]}
  gt: {sub: [0.5], div: [0.5]}

model:
    name: edsr_baseline
    args:
      n_resblocks: 16
      n_feats: 64
      scale: 4


optimizer:
  name: adam
  args:
    lr: 1.e-4
epoch_max: 600
multi_step_lr:
  milestones: [200, 400, 600]
  gamma: 0.5

epoch_val: 1
epoch_save: 100
